name: "Feature Request"
description: "Suggest a new feature or improvement"
title: "[Feature]: "
labels: ["feature"]
body:

  - type: markdown
    attributes:
      value: "Thanks for taking the time to propose a new feature!"

  - type: input
    id: title
    attributes:
      label: Feature Title
      description: Provide a short and clear title for this feature
      placeholder: "Ex: Early Access License Flow"

    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to Solve
      description: Explain **why** this feature should exist. What problem or limitation does it address?
      placeholder: |
        - What is missing?
        - What limitation exists?
        - Why is this needed?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe **what** should be implemented and how it should work.
      placeholder: |
        Describe the workflow, behaviour, and expected output.
    validations:
      required: true
